version: '3.8'

services:
  chat_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - chat-data:/var/lib/postgresql/data

  chat-service:
    restart: always
    build:
      context: ./chat-service
    environment:
      - DB_SERVER=chat_db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
    ports:
      - "8080:8080"
    depends_on:
      - chat_db
    links:
      - chat_db

  chat-web-ui:
    restart: always
    build:
      context: ./chat-web-ui
    ports:
      - "4200:80"

volumes:
  chat-data:
